# version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: agrios
      POSTGRES_PASSWORD: agrios_secret
      POSTGRES_DB: agrios_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
    - "5433:5432"
    environment:
      DATABASE_URL: postgresql://agrios:agrios_secret@postgres:5432/agrios_db
      SECRET_KEY: your_secret_key_here
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data: