services:
  - type: web
    name: agrios-backend
    runtime: python
    repo: https://github.com/Thummutukuri-Pavan-Kumar/AgriOS-AI
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8